### ISSUE TITLE
PostgreSqlConnection doesn't appear to work when Multiplexing has been enabled in the connection string.

### ISSUE THREAD

**Issue by jspaey** [frankhommers/Hangfire.PostgreSql#183] opened 2021-02-28 18:12 UTC
Hi.

Version 5.0 of Npgsql introduced connection multiplexing to provide more efficient use of connections.

I've enabled this in our app and it appears to work quite well so far. Fewer connections are required and idle connections get cleaned up as expected.

However, I've noticed that multiplexing doesn't appear to work with the current version of Hanfire.PostgreSql. 
With multiplexing turned off, the heartbeat timestamp in the state table seems to get updated every 30 seconds.
With multiplexing turned on, the heartbeat timestamp is never updated.

I suspect the cause might be the implementation of PostgreSqlConnection. I see it takes a NpgsqlConnection as a constructor parameter, and holds a reference to this connection for the lifetime of the PostgreSqlConnection instance.  From my understanding, with multiplexing enabled, Npgsql no longer allocates exclusive physical connections. Therefore, holding on to a NpgsqlConnection instance doesn't keep connection alive, which I think is the assumption PostgreSqlConnection is making.

FYI, I have no knowledge of how JobStorageConnection works, so my assumptions might be completely wrong.

Thanks

**Comment by frankhommers** [comment] 2021-08-30 21:06
This might be the cause. But it's at the time of writing an experimental feature of Npgsql. See here: https://www.npgsql.org/doc/release-notes/5.0.html#connection-multiplexing

How would you like this to see in a fixed version?

**Comment by jspaeyids** [comment] 2021-09-27 20:08
Hi Frank,

Besides performing guard checks on each connection operation to ensure the connection is open, I can't think of a clean/reliable way of solving this at moment. As you mentioned, it's still an experimental feature and it's unpredictable how the behaviour might change in future.

At the time, we were trying to achieve multiplexing without the need for pgBouncer.

For now, we've decided to use pgBouncer to achieve the desired behaviour.

Thanks

**Comment by frankhommers** [comment] 2021-09-28 08:12
OK. I'll close this for now then. We'll reopen it when the feature gets out of its experimental phase.

**Closed by frankhommers** 2021-09-28 08:12 UTC
