### ISSUE TITLE
Transactions stuck in the queue

### ISSUE THREAD

**Issue by Jossec101** [frankhommers/Hangfire.PostgreSql#267] opened 2022-10-17 09:11 UTC
Hello there,

We are using jobs that are run every minute, we have identified that after some time (we could say it is random but we did not find any evidence that triggers this behaviour) the job queues won't process any new job, the ongoing jobs are still working flawlessy. The server will also has a heartbeat and it is up and running.  Only a restart of the process will enable the queue to start clearing itself.

We then moved to Hangfire own's `UseSqlServerStorage()` and it is working so far.

Any guidance on debugging this? We could say it is this extension's fault but we don't have any evidence and no log indicates any issue, the queue is simply stuck.

**Comment by azygis** [comment] 2022-10-17 10:42
Let's start somewhere somewhat silly.

Are you sure you don't set the queue polling interval to some very high value?

**Comment by Jossec101** [comment] 2022-10-17 14:22
We did not set any settings, everything was default.
Config settings:
```csharp
                config.UseSerializerSettings(new JsonSerializerSettings()
                {
                    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
                });
                config.UseFilter(new AutomaticRetryAttribute
                {
                    LogEvents = true,
                    Attempts = 20,
                    OnAttemptsExceeded = AttemptsExceededAction.Fail,
                });

                config.UsePostgreSqlStorage(connectionString);
```

**Comment by azygis** [comment] 2022-10-17 15:45
Would you be able to create a minimal runnable project to reproduce the issue?

**Comment by Jossec101** [comment] 2022-10-18 09:53
It is kinda difficult, we only found this happening on our staging environment, do you know any way to trace potential locks or something at db level that would "point" to a bug?

The thing is that with normal MSSQL storage it is working perfectly, so this poitns to a problem with either Hangfire.PostgreSql or Postgres itself.

We are using postgres:13 as a docker image.

**Comment by azygis** [comment] 2022-10-23 14:07
Sorry, I personally may not be able to help without a repro. Chasing the issue without any way to recreate the broken state is pretty impossible. Too many settings to think of having any impact.

Not saying the library is flawless - it's just too hard to tell what's causing all this.

**Comment by azygis** [comment] 2023-01-09 14:59
I've hit pretty much the same issue myself a few weeks back, and it boiled down to one particular data set which would "hang" the whole worker. The job would never complete. Since we did not use cancellation tokens, job would not ever be aborted, until the process restarts. Once all the workers are occupied with the same job (there's an invisibility (I think?) timeout in hangfire, which can cause a "stuck" job starting again), there would no longer be workers to process the subsequent jobs.

This happened exactly on one of our test environments out of 5.

When we noticed that there's always one job that is processing (and never changes), we managed to find the reason in our actual job implementation, and after fixing the job, it all went back to normal. Since there's no such job when switching the providers, it would explain why SQL Server just works - the stuck job is not in that database.

I suggest to check if you have the same issue, which might boil down to a possible bug in the job rather than the library/database. I'll close the issue until further details.

**Closed by azygis** 2023-01-09 14:59 UTC
