### ISSUE TITLE
PostgresException 53300: sorry, too many clients already

### ISSUE THREAD

**Issue by anothercoding** [frankhommers/Hangfire.PostgreSql#124] opened 2019-08-16 15:59 UTC
Hi all,

I initialize Hangfire.Postgres with the name of my connection string.
The same database is used by EntityFramework with the same connection string.

Another issue has the same topic: https://github.com/frankhommers/Hangfire.PostgreSql/issues/85

My EF is using less than 5 connection, all other 95+ are created by Hangfire. is there a way to restrict Hangfire to use a limited number of connections?
Can you advice how to configure Hangfire.PostgreSql ?

Here are my notes:

```
services.AddHangfire(config =>
    {
        config.UsePostgreSqlStorage(Configuration.GetConnectionString("DefaultConnection"));
    }
);
```

As expected, this will be used in PostgreSqlStorage.cs to install Hangfire

```
using (var connection = CreateAndOpenConnection())
{
    PostgreSqlObjectsInstaller.Install(connection, options.SchemaName);
}
```

What I did not expected was to have a increasing number of connections from GetMonitoringApi() because _existingConnection is always null. A new connection is created every 3 seconds when I have the Dashboard open.

```
var connection = _existingConnection ?? CreateAndOpenConnection();
``` 

In few minutes I get the exception:

> PostgresException 53300: sorry, too many clients already

If I change the code to keep and reuse the initial connection as in this example

```
using (var connection = CreateAndOpenConnection())
{
    PostgreSqlObjectsInstaller.Install(connection, options.SchemaName);
}
```

I end up with another exception: 

NpgsqlOperationInProgressException: A command is already in progress

**Comment by JBildstein** [comment] 2019-08-17 12:43
I have exactly the same problem with v1.6.2

After downgrading back to version 1.6.0 it works fine though.

**Comment by mortenju** [comment] 2019-08-17 13:18
Same problem. 1.6.1 works

**Comment by vytautask** [comment] 2019-08-17 15:01
Guys, are sure you’re disposing/closing the connection properly? Cause you have to care of this yourself (as you’re the one who creates it).

**Comment by JBildstein** [comment] 2019-08-17 16:06
I don't think we are creating any connections explicitly. The code that @anothercoding posted is from this very repo: https://github.com/frankhommers/Hangfire.PostgreSql/blob/9e12fe4b2a3234ad6db3638f2e985a555d175e52/src/Hangfire.PostgreSql/PostgreSqlStorage.cs#L93

This is pretty much all my code for Hangfire:
```
public static IServiceCollection AddHangfire(this IServiceCollection services, IConfiguration configuration)
{
    var provider = services.BuildServiceProvider();
    var scopeFactory = (IServiceScopeFactory)provider.GetService(typeof(IServiceScopeFactory));

    services.AddHangfire(c =>
    {
        c.UseActivator(new AspNetCoreJobActivator(scopeFactory));
        c.UsePostgreSqlStorage(
            configuration.GetConnectionString("DefaultConnection"),
            new PostgreSqlStorageOptions { SchemaName = "hangfire" });
        c.UseFilter(new AutomaticRetryAttribute { Attempts = 0 });
        c.UseSerilogLogProvider();
    });

    return services;
}

public static IApplicationBuilder UseHangfire(this IApplicationBuilder app, IConfiguration configuration)
{
    var config = configuration.GetSection("Hangfire");

    app.UseHangfireServer();
    app.UseHangfireDashboard(config["BasePath"]);

    // a bunch of RecurringJob.AddOrUpdate here

    return app;
}
```

Once I open up the Dashboard the error happens after a short while.

**Comment by mortenju** [comment] 2019-08-17 17:07
> I don't think we are creating any connections explicitly. The code that @anothercoding posted is from this very repo:
> 
> https://github.com/frankhommers/Hangfire.PostgreSql/blob/9e12fe4b2a3234ad6db3638f2e985a555d175e52/src/Hangfire.PostgreSql/PostgreSqlStorage.cs#L93
> 
> This is pretty much all my code for Hangfire:
> 
> ```
> public static IServiceCollection AddHangfire(this IServiceCollection services, IConfiguration configuration)
> {
>     var provider = services.BuildServiceProvider();
>     var scopeFactory = (IServiceScopeFactory)provider.GetService(typeof(IServiceScopeFactory));
> 
>     services.AddHangfire(c =>
>     {
>         c.UseActivator(new AspNetCoreJobActivator(scopeFactory));
>         c.UsePostgreSqlStorage(
>             configuration.GetConnectionString("DefaultConnection"),
>             new PostgreSqlStorageOptions { SchemaName = "hangfire" });
>         c.UseFilter(new AutomaticRetryAttribute { Attempts = 0 });
>         c.UseSerilogLogProvider();
>     });
> 
>     return services;
> }
> 
> public static IApplicationBuilder UseHangfire(this IApplicationBuilder app, IConfiguration configuration)
> {
>     var config = configuration.GetSection("Hangfire");
> 
>     app.UseHangfireServer();
>     app.UseHangfireDashboard(config["BasePath"]);
> 
>     // a bunch of RecurringJob.AddOrUpdate here
> 
>     return app;
> }
> ```
> 
> Once I open up the Dashboard the error happens after a short while.

Agreed.

Also this issue is quite apparent if you compare it with previous versions, a downgrade solves the issue, making that suggestion a mute point.

**Comment by mortenju** [comment] 2019-08-17 17:46
One thing might worth noting, i do use custom job activator, as above.

**Comment by vytautask** [comment] 2019-08-19 06:14
Probably is related to `PostgreSqlMonitoringApi.cs` changes, done in https://github.com/frankhommers/Hangfire.PostgreSql/commit/9e12fe4b2a3234ad6db3638f2e985a555d175e52 ...

**Comment by anothercoding** [comment] 2019-08-19 08:58
As @JBildstein suggested a downgrade to version 1.6.0 this proved to be a solution for me. The number of connections does not grow over 11 as in version 1.6.2 there was a additional connection every 3 seconds. Note that I have Entity Framework in the same project using an average 5 connections.

**Comment by zdarovka** [comment] 2019-08-19 09:03
Hello @anothercoding,
I suggest to keep this open as the issue is still valid in the latest version and I think it should be fixed

**Comment by MrkacekVladimir** [comment] 2019-08-19 09:09
@zdarovka upvoted. Problem still persists in 1.6.2 version.

**Comment by vytautask** [comment] 2019-08-20 05:51
I'm pretty sure that this was introduced with https://github.com/frankhommers/Hangfire.PostgreSql/commit/fea679fa0596baafc6e03974143603d9a89bf5a2#diff-f55aa2b50717aabf01c2fcd5651e81e3. Could somebody take a look?

**Comment by Peter-Optiway** [comment] 2019-08-30 13:35
I'm also having this issue, are there any workarounds? (using 1.7.6)

**Comment by riscie** [comment] 2019-08-30 14:44
Downgrading to version 1.6.0 is the workaround I use atm @Peter-Optiway.

**Comment by mortenju** [comment] 2019-08-30 22:20
> I'm also having this issue, are there any workarounds? (using 1.6.2)

1.6.1 is fine for me.

**Comment by frankhommers** [comment] 2019-09-01 21:47
@VincentVrijburg can you look at this? We suspect it's introduced by your PR.

**Comment by VincentVrijburg** [comment] 2019-09-02 05:41
@frankhommers I will take a look later today and see if I can reproduce this issue.

**Comment by VincentVrijburg** [comment] 2019-09-02 17:47
@JBildstein @anothercoding @zdarovka @vytautask @mortenju @frankhommers 
I've found the issue in my own PR and I'm working on a fix as we speak. I'll make a new PR with the fix after I've thoroughly tested it with multiple configurations (manually and using the existing Unit tests).

And I would appreciate it if someone, who had this issue before, can test it with my PR as well when it's out. Let me know If you're able and willing to test it.

**Comment by vytautask** [comment] 2019-09-03 15:20
🎉 PR merged!
Lets have a confirmation it's fixed and then I'll (or somebody) will close this.

**Comment by xumix** [comment] 2019-09-04 16:42
> 
> 
> One thing might worth noting, i do use custom job activator, as above. For the purpose of DI

Same here, even 1024 max connection pool is not enough. This occurs when trying to delete many (1000+) failed or scheduled jobs in UI.
I'm also using Autofac as DI activator.

**Comment by xumix** [comment] 2019-09-04 16:42
> 
> 
> 🎉 PR merged!
> Lets have a confirmation it's fixed and then I (or somebody) will close this.

How do I check this?

**Comment by VincentVrijburg** [comment] 2019-09-08 11:10
@xumix You can check this by using the latest version (1.6.3) from Nuget and see if you get the exception from this issue.

**Comment by riscie** [comment] 2019-09-08 18:10
I had the error before (with 1.6.2). The error occured quite quickly. With 1.6.3 it is running now since 2 hours without errors. So it seems fine :)

**Closed** 2019-09-09 07:35 UTC
Labels: help wanted

**Comment by denis-ivanov** [comment] 2020-07-07 11:03
I have the same problem in 1.7.0.

**Comment by sreilus** [comment] 2020-08-12 20:43
For me, reducing the number of worker solved my problem.

``var options = new BackgroundJobServerOptions { WorkerCount = Environment.ProcessorCount * 3 };
			app.UseHangfireServer(options);

**Comment by PaulARoy** [comment] 2020-08-20 15:10
We experienced this with 1.7.1 with a mac because we were declaring `WorkerCount = Environment.ProcessorCount * 5`.

Turns out the mac has `Environment.ProcessorCount` at 12 (probably 6 + 6 virtual processors), which declared a LOT of workers (60). This caused the limit to rise beyond 100 connexions.

I'm sharing it if that helps anybody in the future.

**Comment by terexk** [comment] 2021-04-29 08:03
@vytautask I don't know why, but the error still occure. 
I use Hangfire.AspNetCore in version 1.7.22 and Hangfire.PostgreSql in version 1.8.4.

My configuration
```
 services.AddHangfire(c =>
   c.UsePostgreSqlStorage(Configuration.GetConnectionString("PostgreSQL"), new PostgreSqlStorageOptions
   {
      DistributedLockTimeout = TimeSpan.FromMinutes(1)
   }));
                
services.AddHangfireServer(c => c.WorkerCount = 3);
```

So, even that I have a small amount of workers, I still get an error:

```
The connection pool has been exhausted, either raise MaxPoolSize (currently 40) or Timeout (currently 15 seconds)
```

It occure in many places, where CreateAndOpenConnection is invoked. Any suggestion, how I can fix it?

```
Npgsql.NpgsqlException:
   at Npgsql.ConnectorPool+<>c__DisplayClass38_0+<<Rent>g__RentAsync|0>d.MoveNext (Npgsql, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlConnection+<>c__DisplayClass41_0+<<Open>g__OpenAsync|0>d.MoveNext (Npgsql, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlConnection.Open (Npgsql, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at Hangfire.PostgreSql.PostgreSqlStorage.CreateAndOpenConnection (Hangfire.PostgreSql, Version=1.8.4.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.PostgreSqlStorage.GetConnection (Hangfire.PostgreSql, Version=1.8.4.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.Server.ServerHeartbeatProcess.Execute (Hangfire.Core, Version=1.7.22.0, Culture=neutral, PublicKeyToken=null)
```

```
Npgsql.NpgsqlException:
   at Npgsql.ConnectorPool+<>c__DisplayClass38_0+<<Rent>g__RentAsync|0>d.MoveNext (Npgsql, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlConnection+<>c__DisplayClass41_0+<<Open>g__OpenAsync|0>d.MoveNext (Npgsql, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Npgsql.NpgsqlConnection.Open (Npgsql, Version=5.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7)
   at Hangfire.PostgreSql.PostgreSqlStorage.CreateAndOpenConnection (Hangfire.PostgreSql, Version=1.8.4.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.PostgreSqlJobQueue+<>c__DisplayClass5_1.<Dequeue_Transaction>b__0 (Hangfire.PostgreSql, Version=1.8.4.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.Utils.Utils.TryExecute (Hangfire.PostgreSql, Version=1.8.4.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.PostgreSqlJobQueue.Dequeue_Transaction (Hangfire.PostgreSql, Version=1.8.4.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.PostgreSqlJobQueue.Dequeue (Hangfire.PostgreSql, Version=1.8.4.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.PostgreSql.PostgreSqlConnection.FetchNextJob (Hangfire.PostgreSql, Version=1.8.4.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.Server.Worker.Execute (Hangfire.Core, Version=1.7.22.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.Server.BackgroundProcessDispatcherBuilder.ExecuteProcess (Hangfire.Core, Version=1.7.22.0, Culture=neutral, PublicKeyToken=null)
   at Hangfire.Processing.BackgroundExecution.Run (Hangfire.Core, Version=1.7.22.0, Culture=neutral, PublicKeyToken=null)
   ```

**Comment by chdphhdhz** [comment] 2021-06-07 02:26
I have the same problem in  1.8.4

**Comment by terexk** [comment] 2021-06-07 06:09
@chdphhdhz In our case we have two types of postgres hosting. The first one is just a linux server with installed postgres, as simple as it can be, and hangfire works here without any issue. The second type of postgres hosting is on kubernetes cluster with pg_pool as a gateway and the mentioned before issue

```The connection pool has been exhausted, either raise MaxPoolSize (currently 40) or Timeout (currently 15 seconds)```

 occurred only here. Our administrator tried modify some part of connection string and since he set two parameters: ConnectionLifetime=600 and Keepalive=15 then no issue occurre now.

**Comment by ttt333** [comment] 2021-07-03 08:46
Hello,
I have the same problem when run hangfire in Kubernetes.  Hangfire.PostgreSql ver. 1.8.4 and 1.8.5.3.
The solution that helped @terexk not work for me

**Comment by bunomonteiro** [comment] 2021-09-15 16:18
Unfortunately, the problem still persists in 1.8.6 version.
And I noticed that the problem occurs with the Dashboard registration.

```csharp
  app.UseHangfireDashboard("<connection_string>"));
```

Is on premises database.

Hangfire.Core: 1.7.25
Hangfire.AspNetCore: 1.7.25
Hangfire.PostgreSql: 1.8.6
PostgreSQL 12.6 (Debian 12.6-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
Debian GNU/Linux 10 (buster)

**Comment by VisualBean** [comment] 2021-11-17 14:20
Definitely still an issue in 1.8.6 .

Im trying to use the monitoringAPI in my integration tests to check when all jobs finished. - but I keep getting this error due to a new connection being created when calling `GetStatistics()`

**Comment by mantasaudickas** [comment] 2021-12-07 22:19
Seems like this stuff is back again.
I suspect its after this PR: https://github.com/frankhommers/Hangfire.PostgreSql/pull/212/commits/deaca23c7c99de005a5fd83d65a827973a506452

Hangfire.Core: 1.7.27
Hangfire.AspNetCore: 1.7.27
Hangfire.PostgreSql: 1.9.3
.NET6

And I cannot revert to 1.8.6 because of this: https://github.com/frankhommers/Hangfire.PostgreSql/issues/214

Problem is that I cannot reproduce it locally, and it happens on one single service when calling:
```
BackgroundJob.Enqueue<ITestJob>(j => j.Run());
```
One call - one hanging connection...

**Comment by iam-black** [comment] 2022-01-14 13:31
Same thing after migrating to .NET 6. Disabling dashboard didn't help. Hangfire.PostgreSql 1.9.5, Npgsql.EntityFrameworkCore.PostgreSQL 6.0.2
I guess current active issue is #163

**Comment by VictorUUsoro** [comment] 2022-03-19 13:40
Same here after migrating to .NET 6

**Comment by ercag** [comment] 2022-10-23 17:07
is there any workaround or fix for this issue?

**Comment by ferenczy** [comment] 2023-02-15 13:37
I had the same issue with Hangfire 1.7.28 and I have found out that it was a problem in my code - I haven't been disposing connections in my job classes.

Originally, I was getting the Hangfire job store connection using the following code:

    var con = Hangfire.JobStorage.Current.GetConnection();

And I was also getting the following error:

> The connection pool has been exhausted, either raise MaxPoolSize (currently 100) or Timeout (currently 15 seconds)

A simple fix was to add the `using` keyword:

    using var con = Hangfire.JobStorage.Current.GetConnection();
