### ISSUE TITLE
"jobid" does not exist for new jobs that fail to execute the first time.

### ISSUE THREAD

**Issue by jcarrey** [frankhommers/Hangfire.PostgreSql#214] opened 2021-11-15 22:31 UTC
This took me a while to figure out, as I thought at first it was a bug executing the job itself, but then thought that my job should be failing otherwise all the jobs should have been failing ,but some worked just fine, and others failed all the time with this error.

```
42703: column "jobid" does not exist
```

The stacktrace points to:
`Hangfire.PostgreSql.PostgreSqlConnection.SetJobParamete`

This is the stack trace :
```
 at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action`2 paramReader) in /_/Dapper/SqlMapper.cs:line 2822
   at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in /_/Dapper/SqlMapper.cs:line 572
   at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 443
   at Hangfire.PostgreSql.PostgreSqlConnection.SetJobParameter(String id, String name, String value)
   at Hangfire.States.ElectStateContext.SetJobParameter[T](String name, T value)
   at Hangfire.AutomaticRetryAttribute.ScheduleAgainLater(ElectStateContext context, Int32 retryAttempt, FailedState failedState)
   at Hangfire.AutomaticRetryAttribute.OnStateElection(ElectStateContext context)
   at Hangfire.States.StateMachine.InvokeOnStateElection(Tuple`2 x)
   at Hangfire.Profiling.ProfilerExtensions.InvokeAction[TInstance](InstanceAction`1 tuple)
   at Hangfire.Profiling.SlowLogProfiler.InvokeMeasured[TInstance,TResult](TInstance instance, Func`2 action, String message)
   at Hangfire.Profiling.ProfilerExtensions.InvokeMeasured[TInstance](IProfiler profiler, TInstance instance, Action`1 action, String message)
   at Hangfire.States.StateMachine.ApplyState(ApplyStateContext initialContext)
   at Hangfire.States.BackgroundJobStateChanger.ChangeState(StateChangeContext context)
   at Hangfire.Server.Worker.TryChangeState(BackgroundProcessContext context, IStorageConnection connection, IFetchedJob fetchedJob, IState state, String[] expectedStates, CancellationToken initializeToken, CancellationToken abortToken)
 ```

**Comment by frankhommers** [comment] 2021-11-16 14:38
Are you sure your install scripts have run correctly?

Here the column gets created:
https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/Scripts/Install.v11.sql

**Comment by jcarrey** [comment] 2021-11-16 14:46
The column does exist, and that's why other jobs run successfully, it's only if the job fails for the first time it executes.

**Comment by frankhommers** [comment] 2021-11-17 10:14
I don't think so. The Convert.ToInt32 would return a 0 or throw an error and JobId would still be filled.

What happens if you execute this statement manually in pgAdmin:

```sql
WITH inputvalues AS (
	SELECT 12345 jobid, 'test' name, 'test' value
), updatedrows AS ( 
	UPDATE hangfire.jobparameter updatetarget
	SET value = inputvalues.value
	FROM inputvalues
	WHERE updatetarget.jobid = inputvalues.jobid
	AND updatetarget.name = inputvalues.name
	RETURNING updatetarget.jobid, updatetarget.name
)
INSERT INTO hangfire.jobparameter(jobid, name, value)
SELECT jobid, name, value 
FROM inputvalues insertvalues
WHERE NOT EXISTS (
	SELECT 1 
	FROM updatedrows 
	WHERE updatedrows.jobid = insertvalues.jobid 
	AND updatedrows.name = insertvalues.name
);
```

**Comment by jherbert** [comment] 2021-11-17 18:03
I ran into this also after upgrading to Npgsql 6.0. I think we're running into this breaking change https://www.npgsql.org/doc/release-notes/6.0.html#parameter-names-now-use-case-sensitive-matching.

**Comment by Gnomit** [comment] 2021-11-18 10:02
> I ran into this also after upgrading to Npgsql 6.0. I think we're running into this breaking change https://www.npgsql.org/doc/release-notes/6.0.html#parameter-names-now-use-case-sensitive-matching.

You are right. The case senstive is the cause.

Also the database columns timestamp must be migrated to timestamptz for the 6.0 version.
My suggestion is to not upgrade to Npgsql 6.0 as long as Hangfire.PostgreSql does not support it.

Or add following lines when starting your application and before any Npgsql operations are invoked:
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);
AppContext.SetSwitch("Npgsql.EnableLegacyCaseInsensitiveDbParameters", true);

**Comment by frankhommers** [comment] 2021-11-21 03:21
I am working on a major code style overhaul. It's in the develop branch right now.
That should handle the jobId problem. Are you also saying there is a Timestamp related problem @Gnomit ?

**Comment by cm-andrews** [comment] 2021-11-21 03:41
i am currently updating my .net 5 project to 6 and have everything working with just the EnableLegacyCaseInsensitiveDbParameters activated. can not reproduce any problems with the timestamp columns.

**Comment by Gnomit** [comment] 2021-11-21 09:18
When EnableLegacyCaseInsensitiveDbParameters activated everything seems to work. 

But in the [release notes of Npgsql 6.0](https://www.npgsql.org/doc/release-notes/6.0.html#major-changes-to-timestamp-mapping) you have the paragraph 'Major changes to timestamp mapping'. When checking the database of hangfire UTC datetimes are stored in columns of the type timestamp (timestamp without time zone). According to the release notes, UTC timestamps should be stored now in a column of type timestamptz (timestamp with time zone), DateTime with Kind=Utc should be used and no use anymore of columns of type timestamp (timestamp without time zone).
During first test I saw no issues but probably there are. Npgsql has added an extra parameter
EnableLegacyTimestampBehavior for this. So I will have an impact somewhere.

Also in the release notes they indicate that if you use Dapper you should upgrade to version 2.0.123 or above.

**Comment by profimedica** [comment] 2021-11-22 23:53
Cause: SQL exects jobid (owercase) but received jobId (camel case)

Please upate this line:
.Execute(sql, new { jobId = Convert.ToInt32(id, CultureInfo.InvariantCulture), name, value }));

**Comment by frankhommers** [comment] 2021-11-23 08:47
We already knew the cause @profimedica, and it's already being developed in the develop branch.

**Comment by isc30** [comment] 2021-11-24 08:45
Hey! also running into this, is there any way I can help?

**Comment by frankhommers** [comment] 2021-11-27 11:51
Should be fixed in next release.

**Closed by frankhommers** 2021-11-27 11:51 UTC
